---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: free5gc-nssf
  labels:
    app.kubernetes.io/version: "v3.1.1"
    project: free5gc
    nf: nssf
spec:
  replicas: 1
  selector:
    matchLabels:
      project: free5gc
      nf: nssf
  template:
    metadata:
      labels:
        project: free5gc
        nf: nssf
    spec:
      containers:
      - name: nssf
        image: towards5gs/free5gc-nssf:v3.1.1
        imagePullPolicy: IfNotPresent
        securityContext:
            {}
        ports:
        - containerPort: 80
        command: ["./nssf"]
        args: ["-c", "../config/nssfcfg.yaml"]
        env: 
          - name: GIN_MODE
            value: release
        volumeMounts:
        - mountPath: /free5gc/config/
          name: nssf-volume
        resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always

      volumes:
      - name: nssf-volume
        projected:
          sources:
          - configMap:
              name: nssf-configmap
