apiVersion: infra.nephio.org/v1alpha1
kind: Network
metadata:
  name: vpc-ran
  annotations:
    config.kubernetes.io/local-config: "true"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  topology: nephio
  routingTables:
  - name: vpc-ran
    prefixes:
    - prefix: 10:2::/32
      labels:
        nephio.org/network-name: n2
    - prefix: 10.10.30.2/24
      labels:
        nephio.org/network-name: n2
    - prefix: 10:3::/32
      labels:
        nephio.org/network-name: n3
    - prefix: 10.10.50.2/24
      labels:
        nephio.org/network-name: n3
    interfaces:
    - kind: bridgedomain
      bridgeDomainName: vpc-ran 
  bridgeDomains: 
  - name: vpc-ran
    interfaces:
    - kind: interface
      selector:
        matchExpressions:
        - {key: nephio.org/cluster-name, operator: Exists}
      attachmentType: none