apiVersion: v1
kind: Secret
metadata:
  name: capi-test-sp-secret
  namespace: default
type: Opaque
stringData:
  clientID: d536949a-76e8-41db-972f-f05134b35566
  clientSecret: Tp78Q~yScYYgInn~4d37Z8ZMCds0soc6C-vuBcrk
  tenantID: 74a56a1c-7c89-4eb7-9fa7-295c71c711e1
---
apiVersion: v1
kind: Secret
metadata:
  name: azure-nephio-control-plane-azure-json
  namespace: default
type: Opaque
data:
  control-plane-azure.json: |
    ewogICJ0ZW5hbnRJZCI6ICI3NGE1NmExYy03Yzg5LTRlYjctOWZhNy0yOTVjNzFjNzExZTEiLAogICJzdWJzY3JpcHRpb25JZCI6ICI5MTQxNGE1ZC05ZDRlLTRiMWEtOGRlNi1kMGE5NWE2ZDA0OTAiLAogICJjbGllbnRJZCI6ICJkNTM2OTQ5YS03NmU4LTQxZGItOTcyZi1mMDUxMzRiMzU1NjYiLAogICJjbGllbnRTZWNyZXQiOiAiVHA3OFF+eVNjWVlnSW5ufjRkMzdaOFpNQ2RzMHNvYzZDLXZ1QmNyayIsCiAgInJlc291cmNlR3JvdXAiOiAiY2FwaS10ZXN0IiwKICAibG9jYXRpb24iOiAiS29yZWEgU291dGgiCn0KCg==
---
apiVersion: v1
kind: Secret
metadata:
  name: azure-nephio-md-0-azure-json
  namespace: default
type: Opaque
data:
  worker-node-azure.json: |
    ewogICJ0ZW5hbnRJZCI6ICI3NGE1NmExYy03Yzg5LTRlYjctOWZhNy0yOTVjNzFjNzExZTEiLAogICJzdWJzY3JpcHRpb25JZCI6ICI5MTQxNGE1ZC05ZDRlLTRiMWEtOGRlNi1kMGE5NWE2ZDA0OTAiLAogICJjbGllbnRJZCI6ICJkNTM2OTQ5YS03NmU4LTQxZGItOTcyZi1mMDUxMzRiMzU1NjYiLAogICJjbGllbnRTZWNyZXQiOiAiVHA3OFF+eVNjWVlnSW5ufjRkMzdaOFpNQ2RzMHNvYzZDLXZ1QmNyayIsCiAgInJlc291cmNlR3JvdXAiOiAiY2FwaS10ZXN0IiwKICAibG9jYXRpb24iOiAiS29yZWEgU291dGgiCn0KCg==
---