---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: free5gc-udm
  labels:
    app.kubernetes.io/version: "v3.1.1"
    project: free5gc
    nf: udm
spec:
  replicas: 1
  selector:
    matchLabels:
      project: free5gc
      nf: udm
  template:
    metadata:
      labels:
        project: free5gc
        nf: udm
    spec:
      containers:
      - name: udm
        image: towards5gs/free5gc-udm:v3.1.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        command: ["./udm"]
        args: ["-c", "../config/udmcfg.yaml"]
        env: 
          - name: GIN_MODE
            value: release
        volumeMounts:
        - mountPath: /free5gc/config/
          name: udm-volume
        resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always

      volumes:
      - name: udm-volume
        projected:
          sources:
          - configMap:
              name: udm-configmap
