apiVersion: fn.kpt.dev/v1alpha1
kind: ApplyReplacements
metadata:
  name: propagate-name
  annotations:
    config.kubernetes.io/local-config: "true"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
replacements:
- source:
    kind: ConfigMap
    name: kptfile.kpt.dev
    fieldPath: data.name
  targets:
  - select:
      kind: Config
    fieldPaths:
    - metadata.namespace
    - spec.config.metadata.namespace
  - select:
      kind: NFConfig
    fieldPaths:
    - metadata.namespace
    - spec.configRefs.0.metadata.namespace
    - spec.configRefs.1.metadata.namespace
    - spec.configRefs.2.metadata.namespace
  # - select:
  #     kind: Interface
  #   fieldPaths:
  #   - metadata.annotations.[specializer.nephio.org/namespace]
  # - select:
  #     kind: Dependency
  #   fieldPaths:
  #   - metadata.annotations.[specializer.nephio.org/namespace]
  - select:
      kind: NetworkAttachmentDefinition
    fieldPaths:
    - metadata.namespace
    # - metadata.annotations.[specializer.nephio.org/namespace]