apiVersion: v1
kind: Service
metadata:
  name: video-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: video
  ports:
    - name: http
      port: 8080        # service port
      targetPort: 8080  # container port
      nodePort: 30080   # optional, must be between 30000–32767
