apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  name: example-flux-helm-controller
spec:
  annotations:
    approval.nephio.org/policy: initial
  upstream:
    package: flux-helm-controllers
    repo: catalog-nephio-optional
    revision: v2.0.0
  downstream:
    package: example-flux-helm-controllers
    repo: mgmt-staging
  injectors:
  - kind: WorkloadCluster
    name: example
  pipeline:
    mutators:
    - image: gcr.io/kpt-fn/set-annotations:v0.1.4
      configMap:
        nephio.org/cluster-name: example