apiVersion: infrastructure.dcnlab.ssu.ac.kr/v1beta1
kind: KTMachineTemplate
metadata:
  labels:
    app.kubernetes.io/name: kt-cloud-operator
    app.kubernetes.io/managed-by: kustomize
  name: kt-cluster1-control-plane
spec:
  template:
    spec:
      flavor: cc39e701-1d52-475d-b4cb-5b61f2216239 #"2x4.itl"
      blockDeviceMapping:
        - id: 6c71bd64-0145-4845-9078-10fdff71ce0e 
          bootIndex: 0
          sourceType: image
          volumeSize: 50
          destinationType: volume
      networkTier:
        - id: 7031a1e3-7435-4cd2-9087-671a995f3bbd
      sshKeyName: kt-cloud-nephio
---
apiVersion: infrastructure.dcnlab.ssu.ac.kr/v1beta1
kind: KTMachineTemplate
metadata:
  labels:
    app.kubernetes.io/name: kt-cloud-operator
    app.kubernetes.io/managed-by: kustomize
  name: kt-cluster1-md-0
spec:
  template:
    spec:
      flavor: cc39e701-1d52-475d-b4cb-5b61f2216239 #id on https://api.ucloudbiz.olleh.com/gd1/server/flavors/detail
      blockDeviceMapping:
        - id: 6c71bd64-0145-4845-9078-10fdff71ce0e # id on https://api.ucloudbiz.olleh.com/gd1/image/images
          bootIndex: 0
          sourceType: image
          volumeSize: 50
          destinationType: volume
      networkTier:
        - id: 7031a1e3-7435-4cd2-9087-671a995f3bbd #refId on https://api.ucloudbiz.olleh.com/gd1/nsm/v1/network
      sshKeyName: kt-cloud-nephio