# apiVersion: velero.io/v1
# kind: Schedule
# metadata:
#   name: core-backup-every-5-min
# spec:
#   schedule: '*/5 * * * *'
#   skipImmediately: false
#   template:
#     excludedNamespaces:
#     - default
#     - kube-node-lease
#     - kube-public
#     - kube-system


apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: example-backup-every-5-min
  namespace: velero  # optional, depending on where you're applying it
spec:
  schedule: '*/5 * * * *'
  skipImmediately: false
  template:
    includedNamespaces:
    - wordpress
