apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: example-md-0
  namespace: default
spec:
  clusterName: example
  replicas: 1
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: example-md-0
      clusterName: example
      failureDomain: compute
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: OpenStackMachineTemplate
        name: example-md-0
      version: v1.32.0
