apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OpenStackMachineTemplate
metadata:
  name: example-md-0
  namespace: default
spec:
  template:
    spec:
      flavor: m1.large
      image:
        filter:
          name: Ubuntu2204-Kube-1.32
      sshKeyName: mykey
