apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: aws-nephio-md-0
  namespace: default
spec:
  template:
    spec:
      preKubeadmCommands:
        - |
          # Download containerd
          curl -LO https://github.com/containerd/containerd/releases/download/v2.1.4/containerd-2.1.4-linux-amd64.tar.gz

          # Extract containerd to a temporary directory
          mkdir -p /tmp/containerd
          tar -xzf containerd-2.1.4-linux-amd64.tar.gz -C /tmp/containerd

          # Stop kubelet and containerd services safely
          systemctl stop kubelet || true
          systemctl stop containerd || true

          # Kill any lingering containerd shim processes
          pkill -9 containerd-shim-runc-v2 || true

          # Copy only containerd binaries explicitly to /usr/local/bin
          cp -f /tmp/containerd/bin/containerd /usr/local/bin/
          cp -f /tmp/containerd/bin/ctr /usr/local/bin/
          cp -f /tmp/containerd/bin/containerd-shim /usr/local/bin/

          # Re-execute systemd daemon and start containerd
          systemctl daemon-reexec
          systemctl start containerd
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            cloud-provider: external
          name: '{{ ds.meta_data.local_hostname }}'
