apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kt-cloud-operator
    control-plane: controller-manager
  name: kt-cloud-operator-system

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kt-cloud-operator
    control-plane: controller-manager
  name: kt-cloud-operator-controller-manager-metrics-service
  namespace: kt-cloud-operator-system
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    control-plane: controller-manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kt-cloud-operator
    control-plane: controller-manager
  name: kt-cloud-operator-controller-manager
  namespace: kt-cloud-operator-system
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --metrics-bind-address=:8443
        - --leader-elect
        - --health-probe-bind-address=:8081
        command:
        - /manager
        env:
        - name: API_BASE_URL
          value: "https://api.ucloudbiz.olleh.com/"
        - name: ZONE
          value: "gd1"
        - name: IDENTITY_METHODS
          value: "password"
        - name: IDENTITY_PASSWORD_USER_DOMAIN_ID
          value: "default"
        - name: IDENTITY_PASSWORD_USERNAME
          value: "soongsil_"
        - name: IDENTITY_PASSWORD
          value: "Qlenfrl!#s24"
        - name: SCOPE_PROJECT_DOMAIN_ID
          value: "default"
        - name: SCOPE_PROJECT_NAME
          value: "soongsil_"
        - name: LOG_LEVEL
          value: "info"
        - name: CLIENT_AUTH_AUTO_RENEW
          value: "true"
        - name: REMOTE_BACKEND_TIMEOUT
          value: "5s"
        image: vitu1/kt-cloud-operator:v0.2
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      securityContext:
        runAsNonRoot: true
      serviceAccountName: kt-cloud-operator-controller-manager
      terminationGracePeriodSeconds: 10
